# Generated by Django 5.0.2 on 2024-02-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expired_at',
            field=models.DateTimeField(),
        ),
    ]
